version: '3'
services:
  userservice:
    build:
      context: ./userservice
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  emailservice:
    build:
      context: ./mailservice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
